version: "3"
services:
  transmission:
    image: linuxserver/transmission:version-3.00-r5
    container_name: "transmission"
    volumes:
      - "/mnt/ssd/containers/config/transmission:/config"
      - "/mnt/tank2/shares/download:/downloads"
    ports:
      - "9091:9091"
      - "51413:51413"
      - "51413:51413/udp"
    networks:
      - "transmission"
    environment:
      PGID: 100
      PUID: 1003
      TZ: "Europe/Paris"
    restart: unless-stopped

  prowlarr:
    image: linuxserver/prowlarr:develop
    container_name: "prowlarr"
    volumes:
      - "/mnt/ssd/containers/config/prowlarr:/config"
    ports:
      - "9696:9696"
    networks:
      - "prowlarr"
      - "transmission"
    environment:
      PGID: 100
      PUID: 1010
      TZ: "Europe/Paris"
    restart: unless-stopped

  radarr:
    image: linuxserver/radarr
    container_name: "radarr"
    volumes:
      - "/mnt/ssd/containers/config/radarr:/config"
      - "/mnt/tank2/shares/download:/downloads"
      - "/mnt/tank2/shares/videos/Films/Films:/movies"
    ports:
      - "7878:7878"
    networks:
      - "transmission"
      - "radarr"
      - "prowlarr"
      - "plex"
    environment:
      PGID: 100
      PUID: 1004
      TZ: "Europe/Paris"
    depends_on:
      - "transmission"
      - "prowlarr"
    restart: unless-stopped

  sonarr:
    image: linuxserver/sonarr:develop
    container_name: "sonarr"
    volumes:
      - "/mnt/ssd/containers/config/sonarr:/config"
      - "/mnt/tank2/shares/download:/downloads"
      - "/mnt/tank2/shares/videos/Séries:/tv"
      - "/mnt/tank2/shares/videos/Anime:/anime"
    ports:
      - "8989:8989"
    networks:
      - "transmission"
      - "sonarr"
      - "prowlarr"
      - "plex"
    environment:
      PGID: 100
      PUID: 1005
      TZ: "Europe/Paris"
    depends_on:
      - "transmission"
      - "prowlarr"
    restart: unless-stopped

  overseerr:
    image: linuxserver/overseerr:latest
    container_name: "overseerr"
    volumes:
      - "/mnt/ssd/containers/config/overseerr:/config"
    ports:
      - "5055:5055"
    networks:
      - "sonarr"
      - "radarr"
      - "plex"
    environment:
      PGID: 100
      PUID: 1012
      TZ: "Europe/Paris"
    depends_on:
      - "sonarr"
      - "radarr"
      - "plex"
    restart: unless-stopped

  plex:
    image: plexinc/pms-docker:latest
    container_name: "plex"
    environment:
      PGID: 100
      PUID: 1002
      TZ: "Europe/Paris"
      VERSION: "latest"
      PLEX_CLAIM: "claim-k7XxtdKj_x9o3geL9yAH"
    volumes:
      - "/mnt/ssd/containers/config/plex:/config"
      - "/mnt/ssd/containers/config/plex/transcode:/transcode"
      - "/mnt/tank2/shares/videos:/data"
      - "/mnt/tank2/shares/musics:/musics"
    ports:
      - "32400:32400/tcp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
      - "32469:32469/tcp"
    networks:
      - "plex"
    restart: unless-stopped

  tdarr:
    container_name: "tdarr"
    image: ghcr.io/haveagitgat/tdarr:latest
    ports:
      - "8265:8265" # webUI port
      - "8266:8266" # server port
    environment:
      TZ: Europe/London
      PUID: 1014
      PGID: 100
      UMASK_SET: 002
      serverIP: 0.0.0.0
      serverPort: 8266
      webUIPort: 8265
      internalNode: true
      inContainer: true
      ffmpegVersion: 6
      nodeName: NasNode
    volumes:
      - "/mnt/ssd/containers/config/tdarr/server:/app/server"
      - "/mnt/ssd/containers/config/tdarr/configs:/app/configs"
      - "/mnt/ssd/containers/config/tdarr/logs:/app/logs"
      - "/mnt/tank2/shares/videos:/media"
      - "/mnt/ssd/containers/config/tdarr_transcode_cache:/temp"
    networks:
      - "tdarr"
    restart: unless-stopped

networks:
  transmission:
  prowlarr:
  sonarr:
  radarr:
  plex:
